#!groovy
pipeline {
    agent {
        docker {
            image 'infernno/androidimage:1.0.0'
        }
    }
    parameters {
        string(name: 'branch', defaultValue: 'development', description: 'Source branh')
    }
    stages {
        stage("Checkout") {
            steps {
                checkout([
                        $class           : 'GitSCM',
                        branches         : [[name: "*/${params.branch}"]],
                        extensions       : [],
                        userRemoteConfigs: [[url: 'https://github.com/Infernno/gamehub.git']]
                ])
            }
        }
        stage('Lint') {
            steps {
                sh "./gradlew lintDebug"
            }
        }
        stage("Test") {
            steps {
                script {
                    if (params.branch.contains('release/')) {
                        sh "./gradlew testReleaseUnitTest"
                    }
                    else {
                        sh "./gradlew testDebugUnitTest"
                    }
                }
            }
        }
        stage("Build") {
            steps {
                script {
                    if (params.branch.contains('release/')) {
                        sh "./gradlew assembleRelease"
                    }
                    else {
                        sh "./gradlew assembleDebug"
                    }
                }
            }
        }
        stage("Publish") {
            steps {
                sh "./gradlew publishToMavenLocal"
            }
        }
    }
    post {
        failure {
            script {
                if (getContext(hudson.FilePath)) {
                    archiveArtifacts(artifacts: '**/build/reports/**', allowEmptyArchive: true)
                }
            }
        }
    }
}
